# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBp6f9poWxXUb5R5ePG2IRjMLGvgiibQ
"""

requirements.txt

streamlit
requests
moviepy