# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBp6f9poWxXUb5R5ePG2IRjMLGvgiibQ
"""

streamlit
requests
moviepy==1.0.1
